
package interfaz;

import business.Person;
import java.util.ArrayList;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.time.LocalDate;
import java.time.Period;

public class CreateJPanel extends javax.swing.JPanel {

	/**
	 * Creates new form ControlJPanel
	 */
	Person person;
	ArrayList<Person> lista;

	public CreateJPanel(Person person, ArrayList<Person> lista) {
		initComponents();
		this.person = person;
		this.lista = lista;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		picTextPath = new javax.swing.JTextField();
		createBtn = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		nameTextField = new javax.swing.JTextField();
		geoTextField = new javax.swing.JTextField();
		dobTextField = new javax.swing.JTextField();
		phoneTextField = new javax.swing.JTextField();
		depTextField = new javax.swing.JTextField();
		ssnTextField = new javax.swing.JTextField();
		emailTextField = new javax.swing.JTextField();
		bankTextField = new javax.swing.JTextField();
		fechaTextField = new javax.swing.JTextField();

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setText("Create Profile");

		jButton1.setText("Select Photo");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		picTextPath.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				picTextPathActionPerformed(evt);
			}
		});

		createBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
		createBtn.setText("Create");
		createBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				createBtnActionPerformed(evt);
			}
		});

		jLabel2.setText("Name: ");

		jLabel3.setText("Geographic Data: ");

		jLabel4.setText("Date of Birth: ");

		jLabel5.setText("Phone: ");

		jLabel6.setText("Departamento");

		jLabel7.setText("Email: ");

		jLabel8.setText("Social Security Number: ");

		jLabel9.setText("Bank Account Number: ");

		jLabel10.setText("Fecha Incorporación");

		emailTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				emailTextFieldActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(59)
						.addGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jLabel8)
										.addComponent(jLabel9).addComponent(jLabel10))
								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(fechaTextField, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
										.addComponent(bankTextField).addComponent(ssnTextField)))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel6)
										.addPreferredGap(ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
										.addComponent(depTextField, GroupLayout.PREFERRED_SIZE, 244,
												GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addComponent(jLabel3)
										.addPreferredGap(ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
										.addComponent(geoTextField, GroupLayout.PREFERRED_SIZE, 244,
												GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(Alignment.TRAILING)
												.addComponent(jLabel5, Alignment.LEADING)
												.addComponent(jLabel4, Alignment.LEADING))
										.addGap(0, 296, Short.MAX_VALUE))
								.addGroup(Alignment.TRAILING,
										layout.createSequentialGroup().addComponent(jLabel7)
												.addPreferredGap(ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
												.addComponent(emailTextField, GroupLayout.PREFERRED_SIZE, 244,
														GroupLayout.PREFERRED_SIZE))
								.addComponent(phoneTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 244,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(dobTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 244,
										GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
										.addPreferredGap(ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
										.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, 244,
												GroupLayout.PREFERRED_SIZE)))
						.addGap(12)
						.addComponent(picTextPath, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(jButton1).addGap(39))
				.addGroup(layout.createSequentialGroup().addGap(372).addGroup(
						layout.createParallelGroup(Alignment.LEADING).addComponent(jLabel1).addComponent(createBtn))
						.addGap(0, 191, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addGap(47)
				.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup().addComponent(jLabel1).addGap(21).addComponent(jLabel2)
								.addGap(18).addComponent(jLabel3))
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addComponent(jButton1).addComponent(picTextPath, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(ComponentPlacement.RELATED).addComponent(geoTextField,
										GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)))
				.addPreferredGap(ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jLabel4).addComponent(dobTextField,
						Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
						GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jLabel5).addComponent(
						phoneTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
						GroupLayout.PREFERRED_SIZE))
				.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
						.addGroup(layout.createSequentialGroup().addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(depTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED).addComponent(emailTextField,
										GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGroup(
								layout.createSequentialGroup().addGap(11).addComponent(jLabel6)
										.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jLabel7)))
				.addPreferredGap(ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(Alignment.TRAILING).addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel8).addComponent(
								ssnTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(jLabel9))
						.addComponent(bankTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel10).addComponent(
						fechaTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
						GroupLayout.PREFERRED_SIZE))
				.addGap(48).addComponent(createBtn).addContainerGap(46, Short.MAX_VALUE)));
		this.setLayout(layout);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		JFileChooser chooser = new JFileChooser();
		chooser.showOpenDialog(null);
		File f = chooser.getSelectedFile();
		String fileName = f.getAbsolutePath();
		picTextPath.setText(fileName);

	}// GEN-LAST:event_jButton1ActionPerformed

	private void picTextPathActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_picTextPathActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_picTextPathActionPerformed

	private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {
	
		String name = nameTextField.getText();
		String geo = geoTextField.getText();
		String phone = phoneTextField.getText();
		String email = emailTextField.getText();
		String bank = bankTextField.getText();
		String dob = dobTextField.getText();
		String ssn = ssnTextField.getText();
		String pathFoto = picTextPath.getText();
		String depto = depTextField.getText();

		if (!name.matches("^[A-Za-z ]{1,50}$")) {
			JOptionPane.showMessageDialog(this,"Nombre no válido");
			return;
		}
		if (!geo.matches("^[A-Za-z ]{1,50}$")) {
			JOptionPane.showMessageDialog(this,"País no válido");
			return;
		}
		if (!phone.matches("^[67]\\d{8}$")) {
			JOptionPane.showMessageDialog(this,"Teléfono no válido");
			return;
		}
		if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
			JOptionPane.showMessageDialog(this,"Email no válido");
			return;
		}
		if (!bank.matches("^ES\\d{22}$")) {
			JOptionPane.showMessageDialog(this,"Cuenta bancaria no válida");
			return;
		}
		if (!dob.matches("^\\d{4}-\\d{2}-\\d{2}$")) {
			JOptionPane.showMessageDialog(this,"Fecha de nacimiento no válida (YYYY-MM-DD)");
			return;
		}
		if (!ssn.matches("^\\d{10}$")) {
			JOptionPane.showMessageDialog(this,"Seguridad Social no válida");
			return;
		}

		try {
			LocalDate fechaNac = LocalDate.parse(dob);
			LocalDate hoy = LocalDate.now();
			int edad = Period.between(fechaNac, hoy).getYears();

			if (edad < 18) {
				JOptionPane.showMessageDialog(this, "Debe ser mayor de 18 años. Edad: " + edad);
				return;
			}

			person.setFechaIncorporacion(hoy.toString());

		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "Error en el formato de fecha");
			return;
		}

		person.setName(name);
		person.setGeographic_data(geo);
		person.setPhone(phone);
		person.setEmail(email);
		person.setBankAccNum(bank);
		person.setDob(dob);
		person.setSsn(ssn);
		person.setImageTxt(pathFoto);

		if (depto.equalsIgnoreCase("TIC")) {
			person.setDepartment(Person.Departamento.TIC);
		} else if (depto.equalsIgnoreCase("Marketing")) {
			person.setDepartment(Person.Departamento.Marketing);
		} else if (depto.equalsIgnoreCase("Administrativo")) {
			person.setDepartment(Person.Departamento.Administrativo);
		}else {
		JOptionPane.showMessageDialog(this, "Departamento inválido (TIC, Marketing o Administrativo)");
		return;
		}
		lista.add(person);
		JOptionPane.showMessageDialog(null, "Profile created successfully !!!");

	}
// GEN-LAST:event_createBtnActionPerformed

	private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailTextFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_emailTextFieldActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField bankTextField;
	private javax.swing.JButton createBtn;
	private javax.swing.JTextField dobTextField;
	private javax.swing.JTextField emailTextField;
	private javax.swing.JTextField depTextField;
	private javax.swing.JTextField geoTextField;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField fechaTextField;
	private javax.swing.JTextField nameTextField;
	private javax.swing.JTextField phoneTextField;
	private javax.swing.JTextField picTextPath;
	private javax.swing.JTextField ssnTextField;
	// End of variables declaration//GEN-END:variables
}