/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import business.Person;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Dario
 */
public class MainJFrame extends javax.swing.JFrame {

	/**
	 * Creates new form MainJFrame
	 */

	Person person;
	ArrayList<Person> lista = new ArrayList<Person>();
	int id = 0;

	public MainJFrame() {
		initComponents();
		this.setSize(1000, 800);
		//person = new Person();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jSplitPane1 = new javax.swing.JSplitPane();
		controlJPanel = new javax.swing.JPanel();
		createPerson = new javax.swing.JButton();
		viewPerson = new javax.swing.JButton();
		displayJPanel = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		createPerson.setText("Create Profile");
		createPerson.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				createPersonActionPerformed(evt);
			}
		});

		viewPerson.setText("Display Profile");
		viewPerson.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				viewPersonActionPerformed(evt);
			}
		});

		JButton btnAnterior = new JButton("Anterior");
		btnAnterior.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (id > 0) {
					id--;
					DisplayJPanel viewJPanel = new DisplayJPanel(lista, id);
					jSplitPane1.setRightComponent(viewJPanel);
				} else {
					javax.swing.JOptionPane.showMessageDialog(null, "Ya estás en el primer perfil.");
				}
			}
		});

		JButton btnSiguiente = new JButton("Siguiente");
		btnSiguiente.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (id < lista.size() - 1) {
					id++;
					DisplayJPanel viewJPanel = new DisplayJPanel(lista, id);
					jSplitPane1.setRightComponent(viewJPanel);
				} else {
					javax.swing.JOptionPane.showMessageDialog(null, "Ya estás en el último perfil.");
				}
			}
		});

		javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
		controlJPanelLayout.setHorizontalGroup(controlJPanelLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(controlJPanelLayout.createSequentialGroup().addContainerGap()
						.addGroup(controlJPanelLayout.createParallelGroup(Alignment.LEADING).addComponent(viewPerson)
								.addComponent(createPerson)
								.addGroup(controlJPanelLayout.createParallelGroup(Alignment.TRAILING, false)
										.addComponent(btnAnterior, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnSiguiente, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		controlJPanelLayout.setVerticalGroup(controlJPanelLayout.createParallelGroup(Alignment.LEADING)
				.addGroup(controlJPanelLayout.createSequentialGroup().addGap(123).addComponent(createPerson).addGap(49)
						.addComponent(btnAnterior).addGap(18).addComponent(btnSiguiente).addGap(31)
						.addComponent(viewPerson).addContainerGap(159, Short.MAX_VALUE)));
		controlJPanel.setLayout(controlJPanelLayout);

		jSplitPane1.setLeftComponent(controlJPanel);

		javax.swing.GroupLayout displayJPanelLayout = new javax.swing.GroupLayout(displayJPanel);
		displayJPanel.setLayout(displayJPanelLayout);
		displayJPanelLayout.setHorizontalGroup(displayJPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 515, Short.MAX_VALUE));
		displayJPanelLayout.setVerticalGroup(displayJPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 472, Short.MAX_VALUE));

		jSplitPane1.setRightComponent(displayJPanel);

		getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

	}// </editor-fold>//GEN-END:initComponents

	private void createPersonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createPersonActionPerformed
		// TODO add your handling code here:
		Person nuevaP = new Person();
		CreateJPanel createJPanel = new CreateJPanel(nuevaP, lista);
		jSplitPane1.setRightComponent(createJPanel);

	}// GEN-LAST:event_createPersonActionPerformed

	private void viewPersonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_viewPersonActionPerformed
		// TODO add your handling code here:
		if (!lista.isEmpty()) {
			this.id = lista.size() - 1;
			DisplayJPanel viewJPanel = new DisplayJPanel(lista, id);
			jSplitPane1.setRightComponent(viewJPanel);
		} else {
			javax.swing.JOptionPane.showMessageDialog(null, "No hay perfiles. Crea uno primero.");
		}
	}// GEN-LAST:event_viewPersonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainJFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel controlJPanel;
	private javax.swing.JButton createPerson;
	private javax.swing.JPanel displayJPanel;
	private javax.swing.JSplitPane jSplitPane1;
	private javax.swing.JButton viewPerson;
}